custom_css = [] 
custom_js = [] 
description = "技術ブログだったりコラムだったりエッセイだったり。" 
logoText = "aiandrox.data" 
logoType = "short" # long, short
meta_image = "" 
themecolor = "" 
useFaviconGenerator = true # https://www.favicon-generator.org/

notAllowedTypesInArchive = ["about", "talks", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHome = ["contact", "talks", "about", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeFeed = ["about", "archive", "contact", "talks", "showcase", "publication", "presentation", "resume", "gallery"]
notAllowedTypesInHomeSidebar = ["about", "archive", "showcase", "publication", "presentation", "resume"]
themeOptions = ["dark", "light", "hacker", "solarized", "kimbie"]

enablePinnedPosts = true 
enableUiAnimation = true 
hideSingleContentsWhenJSDisabled = false 
minItemsToShowInTagCloud = 1 # Minimum items to show in tag cloud
viewportSize = "normal" # widest, wider, wide, normal, narrow

# header
homeHeaderType = "text" # text, img, slide

# menu
showMobileMenuTerms = ["tags", "categories", "series"]

# body
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 20 
enableBreadcrumb = true 
enableGoToTop = true 
enablePhotoSwipe = true 
enableSearch = true 
enableSearchHighlight = true 
enableWhoami = true 
paginateWindow = 1 
pubPaginate = 20 
searchResultPosition = "main" # side, main
summaryShape = "classic" # card, classic, compact
talksGroupByDate = "2006" 
talksPaginate = 5 

# whoami
bioImageUrl = "/images/whoami/avatar_wide.jpg"
email = "aiandrox7@gmail.com"
link = "https://aiandrox.netlify.app"
location = "Tokyo, Japan"
myname = "aiandrox"
# organization = "Hugo"
useGravatar = false
whoami = "自己肯定感強いマン"

# sidebar
enableBio = true 
enableBioImage = true 
enableHomeSidebarTitles = true 
enableListSidebarTitles = true 
enableSidebar = true 
enableSidebarCategories = true 
enableSidebarPostsByOrder = false 
enableSidebarSeries = true 
enableSidebarTags = true 
enableToc = true 
enableTocSwitch = true 
hideToc = false 
itemsPerCategory = 5 
sidebarPosition = "right" 
tocFolding = true 
tocLevels = ["h2", "h3", "h4"] 
tocPosition = "inner" # inner, outer

# footer
enableLangChange = false
enableThemeChange = false
showFeedLinks = true
showPoweredBy = true
showSocialLinks = false

# service
baiduAnalytics = "" 
busuanziPagePV = true 
busuanziSitePV = true 
busuanziSiteUV = true 
enableBusuanzi = false 
googleTagManager = "" # GTM-XXXXXX

# rss
fullContents = false 
updateFrequency = "" 
updatePeriod = "" # Possible values: 'hourly', 'daily', 'weekly', 'monthly', or 'yearly'.

# comment
commento = false
disqus_shortname = ""
enableComment = true

[telegram]
dataLimit = 5
enable = false
siteId = ""

[gitment] # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
clientId = "" # Your client ID
clientSecret = "" # Your client secret
owner = "" # Your GitHub ID
repo = "" # The repo to store comments

[utterances] # https://utteranc.es/
owner = "" # Your GitHub ID
repo = "" # The repo to store comments

[gitalk] # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
clientId = "" # Your client ID
clientSecret = "" # Your client secret
owner = "" # Your GitHub ID
repo = "" # The repo to store comments

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[valine]
appId = '你的appId' 
appKey = '你的appKey' 
avatar = 'mm' 
enable = false 
notify = false # mail notifier , https://github.com/xCss/Valine/wiki
placeholder = '说点什么吧...' 
verify = false # Verification code
visitor = false 

[changyan]
changyanAppid = "" # Changyan app id             # 畅言
changyanAppkey = "" # Changyan app key

[livere]
livereUID = "" # LiveRe UID                  # 来必力

# Isso: https://posativ.org/isso/
[isso]
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"
enable = false 
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"

[socialOptions]
csdn = ""
dev-to = ""
douban = ""
email = "mailto:aiandrox7@gmail.com"
facebook = ""
gitea = ""
github = "https://github.com/aiandrox"
gitlab = ""
google-plus = ""
google-scholar = ""
instagram = "https://www.instagram.com/k_end715"
jianshu = ""
linkedin = ""
mastodon = ""
matrix = ""
medium = ""
phone = ""
pinterest = ""
signal = ""
stack-exchange = ""
stack-overflow = ""
steam = ""
telegram = ""
tumblr = ""
twitter = "http://twitter.com/aiandrox"
weibo = ""
whatsapp = ""
xmpp = ""
youtube = ""
zhihu = ""

[donationOptions]
alipay = ""
enable = false
patreon = ""
paypal = ""
wechat = ""

# possible share name: ["facebook","twitter", "reddit", "linkedin", "tumblr", "weibo", "douban", "line"]
[[share]]
name = "facebook"
username = ""
[[share]]
name = "twitter"

[[footerLinks]]
link = ""
name = ""
[[footerLinks]]
link = ""
name = ""
